// <auto-generated />
using System;
using MailMeDataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MailMeDataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231212223000_mig_edit_identity")]
    partial class mig_edit_identity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailMeEntityLayer.Concrete.PersonalAccount", b =>
                {
                    b.Property<int>("PersonalAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonalAccountId"));

                    b.HasKey("PersonalAccountId");

                    b.ToTable("PersonalAccounts");
                });

            modelBuilder.Entity("MailMeEntityLayer.Concrete.PersonalAccountProcess", b =>
                {
                    b.Property<int>("PersonalAccountProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonalAccountProcessId"));

                    b.Property<DateTime>("ProcessDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcessType")
                        .HasColumnType("integer");

                    b.HasKey("PersonalAccountProcessId");

                    b.ToTable("PersonalAccountProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
